
env._type: cluster-env


#task-command: singularity run --nv --bind ~/workspace/singe/data/:/data ~/workspace/singe/text-generation-inference.sif --port {port} -e
task-command: singularity run --nv --bind ~/workspace/singe/data/:/data --bind ~/.cache/huggingface/:/cache --env HF_HOME=/cache ~/workspace/singe/text-generation-inference.sif --port {port}


#working-dir: /home/fleeb/workspace/code/llm-evaluation
repo-working-dir: yes

time-limit: 10

bid: 50


#job_id:
#  _type: env-var
#  var: JOB_ID
#
#job_name:
#  _type: env-var
#  var: JOB_NAME


