
env._type: cluster-env


command: singularity run --nv --bind ~/workspace/singe/data/:/data ~/workspace/singe/text-generation-inference.sif' --port {port} -e


#job_id:
#  _type: env-var
#  var: JOB_ID
#
#job_name:
#  _type: env-var
#  var: JOB_NAME


