

_meta.script_name: run


dataset:
  _type: mmlu/single
#  path: /clones/mmlu/data/conceptual_physics_dev.csv
  path: C:/Users/anwan/OneDrive/Khan/research/clones/mmlu/data/conceptual_physics_dev.csv


benchmark:
  _type: simple


metrics:
  - correct


env.score:
  _type: equals
  app:
    a: answer
    b: pick
    isequal: correct


env.agent:
  _type: randint
  options: 4





