
_meta.script_name: start-server

app._type: manager-server

manager._type: job-manager

config_root._type: default-config-root




#root: test-job-root


#4bit: yes
#8bit: no
#device: cuda
#
#model-id: microsoft/phi-2
#
#model_args:
#  trust_remote_code: yes
#  device_map: <>device
#  load_in_4bit: <>4bit
#  load_in_8bit: <>8bit
#
#tokenizer_args:
#  trust_remote_code: yes
#  device_map: <>device

