

_meta.script_name: run

_base: [mmlu]

dataroot: ~/workspace/local_data/MMLU

topic: health

split: val


out-dir: local_tasks/


env.agent:
  _type: randint
  options: 4

env.score:
  _type: equals
  app:
    a: answer
    b: pick
    isequal: correct


#dataset:
#  _type: mmlu/single
#  path: ../clones/mmlu/data/conceptual_physics_dev.csv
##  path: C:/Users/anwan/OneDrive/Khan/research/clones/mmlu/data/conceptual_physics_dev.csv
#
#
#benchmark:
#  _type: generic
#
#
#agg:
#  - correct
#
#log:
#  - index
#  - question
#  - pick
#  - correct
#
#selection: <>log
#




